version: 0.0
os: ubuntu 
files:
 - source: /ec2django/
   destination: /home/ubuntu/bluemuffins/ec2django
 - source: /helloworld/
   destination: /home/ubuntu/bluemuffins/helloworld
 - source: /manage.py
   destination: /home/ubuntu/bluemuffins
 - source: /supervisord.conf
   destination: /home/ubuntu/bluemuffins
 - source: /requirements.txt
   destination: /home/ubuntu
 - source: /requirements/
   destination: /home/ubuntu/bluemuffins/requirements

permissions:
  - object: /home/ubuntu/bluemuffins/manage.py
    owner: ubuntu 
    mode: 644
    type:
      - file
  - object: /home/ubuntu/bluemuffins/supervisord.conf
    owner: ubuntu 
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
